[package]
name = "Synima"
version = "2.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
colored = "3.0"
which = "8"
rayon = "1.10"
regex = "1"
rust-embed = "8"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"